In [57]:
import numpy as np
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth

In [59]:
df = pd.read_csv("heart.csv")

In [60]:
df

,age,sex,chest_pain_type,resting_bp,cholestoral,fasting_blood_sugar,restecg,max_hr,exang,oldpeak,slope,num_major_vessels,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [62]:
te = TransactionEncoder()
te_ary = te.fit(df.values.tolist()).transform(df.values.tolist())
df = pd.DataFrame(te_ary, columns=te.columns_)

In [63]:
from timeit import default_timer
start = default_timer()
association_rules = fpgrowth(df, min_support=0.6)
duration = default_timer() - start
print(duration)
association_results = list(association_rules)

0.004668300010962412

In [64]:
print(association_rules)

    support     itemsets
0  1.000000          (0)
1  0.990099         (10)
2  0.805281         (19)
3  0.990099      (0, 10)
4  0.805281      (0, 19)
5  0.798680     (10, 19)
6  0.798680  (0, 10, 19)